/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.awt.Component;

import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.util.logging.Level;

import java.util.logging.Logger;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class book extends javax.swing.JFrame {

    /**
     * Creates new form book
     */
    public book() {
        initComponents();
        setPersonTableData();
    }
 public static Connection myConnection(){

                    	Connection con = null;

	   try{

    	    Class.forName("com.mysql.jdbc.Driver"); // load the  JDBC driver for MySQL.

 

                String connectionUrl="jdbc:mysql://localhost:3306/javadb?"+"user=root&password="; //    

        	con = DriverManager.getConnection(connectionUrl);  //  establish a database connection with the server via its getConnection() method

 	 

    	} catch (ClassNotFoundException ex) {

 	Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

    	} catch (SQLException ex) {

 	Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

    	}

     	return con;
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("BOOK DETAILS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Product Code");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));
        jPanel1.add(pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 231, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, 20));

        bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnActionPerformed(evt);
            }
        });
        jPanel1.add(bn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Author");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 220, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Categories");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Short Story", "Autobiography", "Drama", "Literary Fiction", "True Crime", "Memoir", "Children's Literature", "Religion", "Humor", "Travel Literature", "Poetry", "Biography", "History", "Mystery", "Fantasy", "Science Fiction", "Self-Help Book", "Fiction", "Non_Fiction", "Horror", "Thriller", "Novel", " ", " ", " " }));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));
        jPanel1.add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 120, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("Book Stock");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 217, 231));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product code", "Title", "Author", "Category", "Quantity", "Price"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 860, 180));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 80, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, 80, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("<-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 56, -1));

        jButton6.setText("Print");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\java\\finalprojava\\bookshop\\project\\project\\src\\project\\bookfinal.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1230, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 306, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int okcancel(String theMessage){

        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);

    	return result;

	}
    private void bnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
String selectedValue = c.getSelectedItem().toString();
// TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// (for date) SimpleDateFormat Dformat = new SimpleDateFormat("dd-MM-yyyy");

        Connection con = myConnection();

   	try{

       	String sql="INSERT INTO booktbl(`product_code`,`title`,`author`,`category`,`quantity`,`price`) VALUES (?,?,?,?,?,?)";

                        	
 

       	PreparedStatement prest,prest2;

       	prest = con.prepareStatement(sql);
        
             //prest.setString(1,i.getText());
             prest.setString(1,pc.getText());
             prest.setString(2,bn.getText());
             //prest.setString(3,Dformat.format(jDateChooser1.getDate()));
             prest.setString(3,a.getText());
             prest.setString(4,(String) c.getSelectedItem());
             prest.setString(5,p.getText());
             prest.setString(6,q.getText());
        

        int count = prest.executeUpdate();

       	if(count>0){

           	int i = okcancel("Book has been Added?");

           	System.out.println("ret:"+i);

              	new book().setVisible(true);

              	dispose();

              	con.close();

       	}
} catch (SQLException ex) {

        	Logger.getLogger(users.class.getName()).log(Level.SEVERE, null, ex);

    	}      	 


     	         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
       	Connection con = myConnection();

 

    	if(id!=0){

        	try{

            	PreparedStatement prest;

 String sql ="delete from booktbl where id="+id;

prest= con.prepareStatement(sql);

 prest.execute(sql);

  new book().setVisible(true);

  dispose();

  con.close();

 resetData();
} 	catch (SQLException ex) {

                  	Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

                }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Connection con = myConnection();
        	int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
 

    	if(id !=0) {

           // String user_id= i.getText();	
            String product_code= pc.getText();
            String title= bn.getText();
            String author= a.getText();
            String category= c.getSelectedItem().toString();
            
     	    String quantity= q.getText();
           String price= p.getText();

try{

 

PreparedStatement prest;

String sql ="update booktbl set product_code='"+product_code+"',title='"+title+"',author='"+author+"',category='"+category+"',price='"+price+"',quantity='"+quantity+"' where id='"+id+"'";
prest= con.prepareStatement(sql);

 prest.execute(sql);

 new book().setVisible(true);

  dispose();

  con.close();

  resetData();

  id =0;

}   catch (SQLException ex) {

    Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

            }

    	}
                           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
   private JFrame frame;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       pc.setText(""); 
       bn.setText(""); 
       a.setText(""); 
       c.setSelectedIndex(5);
       p.setText("");  
       q.setText("");  
       
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());


   	Connection con = myConnection();

try{

PreparedStatement prest;

String sql ="select * from booktbl where id="+id;

prest= con.prepareStatement(sql);

ResultSet rs = prest.executeQuery(sql);
while(rs.next()){
        //i.setText(rs.getString(2));
	pc.setText(rs.getString(2));
        bn.setText(rs.getString(3));
        a.setText(rs.getString(4));
	//c.setSelectedItem(rs.getValueAt(5).toString());
        p.setText(rs.getString(6));
        q.setText(rs.getString(7));
}

 rs.close();

 prest.close();


}   	catch (SQLException ex) {

        	Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

    	}
	              // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     new admin().setVisible(true);   
     dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
try{
    jTable1.print();
}catch(Exception e){
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField bn;
    private javax.swing.JComboBox<String> c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField p;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField q;
    // End of variables declaration//GEN-END:variables

    private void resetData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void setPersonTableData(){
	Connection con = myConnection();
   	try{
PreparedStatement prest;
String sql ="select * from booktbl";
prest= con.prepareStatement(sql);
ResultSet rs = prest.executeQuery(sql);
while(rs.next()){
    
   String id  = String.valueOf(rs.getInt("id"));
   String proc = rs.getString("product_code");
   String tit = rs.getString("title");
  	String au = rs.getString("author");
        String c = rs.getString("category");
       	String qa = rs.getString("quantity");
         String pr = rs.getString("price");
    
        	String tbData[]={id,proc,tit,au,c,qa,pr};
        	DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        	tblModel.addRow(tbData);

   	}
   	}catch (SQLException ex) {
        	Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);
    	}
}
}


