/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.String.valueOf;
import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import static bookstore.book.myConnection;
//import static stockmanagement.addcashier.okcancel;
import java.sql.ResultSet;
import static javax.swing.UIManager.getInt;
import static project.users.myConnection;
import static project.users.okcancel;

/**
 *
 * @author Acer
 */
public class createbill extends javax.swing.JFrame {

    /**
     * Creates new form createbill
     */
    public createbill() {
        initComponents();
        Dimension dim = (Toolkit.getDefaultToolkit()).getScreenSize();
        setSize(dim);
        //setBillTableData();
        
    }

    private void setBillTableData(){

    Connection con = myConnection();

       try{

PreparedStatement prest;

String sql ="select * from bill";

prest= con.prepareStatement(sql);

java.sql.ResultSet rs = (java.sql.ResultSet) prest.executeQuery(sql);

 

while(rs.next()){

   

   //String id  = String.valueOf(rs.getInt("billid"));

   String fn = rs.getString("id");
   
   String pn = rs.getString("title");

      String qn = rs.getString("quantity");
      
      String pr = rs.getString("lineprice");

            

            String tbData2[]={fn,pn,qn,pr};

            DefaultTableModel tblModel2=(DefaultTableModel)createbill.getModel();

            tblModel2.addRow(tbData2);

 

       }

       }catch (SQLException ex) {

            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dte = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        createbill = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        qntity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pronme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cusname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addrs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Create Bill");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 49, -1, -1));

        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 231, -1, 10));
        jPanel1.add(dte, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 225, 142, -1));

        createbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(createbill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 151, -1, 181));

        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 367, -1, -1));
        jPanel1.add(qntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 364, 142, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 422, -1, -1));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 364, 153, -1));

        jLabel9.setText("Phone Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 194, -1, -1));
        jPanel1.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 191, 142, -1));

        jButton3.setBackground(new java.awt.Color(102, 255, 255));
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 253, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 255, 255));
        jButton4.setText("TOTAL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 364, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 255, 255));
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 448, -1, -1));

        jLabel5.setText("Product Name");

        jLabel2.setText("Customer Name");

        jLabel4.setText("Address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(pronme, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addrs))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pronme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 820, 450));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int bl_id;
    int pr_id,pro_id,pri,qn;
    PreparedStatement st;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection();

       try{

           String p_nb=pronme.getText();
           String q_nb=qntity.getText();
           //String sql3="INSERT INTO billmaster(`custname`,`date`) VALUES (?,?)";
           String sql="INSERT INTO bill(`title`,`quantity`,`price`) VALUES (?,?,?)";
           //String sql_1="SELECT price FROM product where productid="+proid.getText();

                            //name given in the table

           
           
           String sql6="SELECT billid FROM billmaster where cname='"+cusname.getText()+"' AND phone='"+ph.getText()+"'";
           String sql2="UPDATE bill SET lineprice=quantity*price";
           
           
 

           PreparedStatement prest,prest2,prest4,prest6,prest7,prest_1,prest_4,prest_5;

           //prest3 = con.prepareStatement(sql3);
           prest = con.prepareStatement(sql);
           prest2 = con.prepareStatement(sql2);
           prest6 = con.prepareStatement(sql6);
           //prest_1 = con.prepareStatement(sql_1);
           //ResultSet prid=prest_1.executeQuery(sql_1);
           //while(prid.next())
            //{
           //pr_id  = prid.getInt("price");
           
            //}
           
           
           //Date date = dte.getDate();
           //String strDate = DateFormat.getDateInstance().format(date);
           
           //prest3.setString(1, cusname.getText());
           //prest3.setString(2,strDate);

           

            // n is the variable name for the text field. To add variable name right click the text field->change variablename.

           
           
           //prest.setString(1,proid.getText());
           
           prest.setString(1,pronme.getText());
           
           prest.setString(2,qntity.getText());
           
           
           
           String cn=cusname.getText();
           String phn=ph.getText();
           int pho=Integer.parseInt(phn);
           
           //prest6.setString(1,cn);
       //prest6.setInt(2,pho);
           
           
       String sql4="INSERT INTO billfinal(`title`,`quantity`,`price`,`cname`,`phone`) VALUES (?,?,?,?,?)";
       prest4 = con.prepareStatement(sql4);
       String sql_4="SELECT price FROM booktbl where title='"+pronme.getText()+"'";
       prest_4 = con.prepareStatement(sql_4);
           ResultSet pricee=prest_4.executeQuery(sql_4);
           while(pricee.next())
            {
           pri  = pricee.getInt("price");
           //System.out.println(pri);
           
            }
       
       String sql_5="SELECT quantity FROM booktbl where title='"+pronme.getText()+"'";
       prest_5 = con.prepareStatement(sql_5);
           ResultSet qntyy=prest_5.executeQuery(sql_5);
           while(qntyy.next())
            {
           qn  = qntyy.getInt("quantity");
           //System.out.println(pri);
           
            }
           
           //prest4.setString(1,proid.getText());
           prest.setInt(3,pri);
           prest4.setString(1,pronme.getText());
           
           prest4.setString(2,qntity.getText());
           
           prest4.setInt(3,pri);
           
           prest4.setString(4,cusname.getText());
           
           prest4.setString(5,ph.getText()); 
           
           /*prest4.setString(1,proid.getText());
           
           prest4.setString(2,pronme.getText());
           
           prest4.setString(3,qntity.getText());
           
           prest4.setInt(4,pri);
           
           prest4.setString(5,cusname.getText());
           
           prest4.setString(6,ph.getText());*/
           
           
           
            String sqlstup="UPDATE `booktbl` SET `quantity`=`quantity` - '"+qntity.getText()+"' WHERE `title`='"+pronme.getText()+"'";
     //Connection con;
   
  // ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/javadb", "root", "");
            st=con.prepareStatement(sqlstup);  
            //st.setString(1, tmp);
            
            
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }

           if(p_nb.equals(""))
           {
               int i2 = okcancel("Product Name cannot be Empty!!");

               System.out.println("ret:"+i2);
           }

           if(q_nb.equals(""))
           {
               
              
               int i3 = okcancel("Quantity cannot be Empty!!");

               System.out.println("ret:"+i3);
               
           }
           int qn_b=Integer.parseInt(q_nb);
           //int qn_c=Integer.parseInt();
           
            
               if(qn_b==0)
               {
                   int i3 = okcancel("Quantity cannot be Zero!!");

               System.out.println("ret:"+i3);
               }
               if(qn_b>qn)
               {
                   int i3 = okcancel("No Sufficient Stock Available!! Please do a Reorder.");

               System.out.println("ret:"+i3);
               }
               else{
                   int count = prest.executeUpdate();
           int lp = prest2.executeUpdate();
           int bf = prest4.executeUpdate();
           st.executeUpdate(sqlstup);
             ResultSet b_id= prest6.executeQuery(sql6);
               
           

 

           //int bm=prest3.executeUpdate();
           
            
            while(b_id.next())
            {
           bl_id  = b_id.getInt("billid");
           //System.out.println(bl_id);
            }
            
             DefaultTableModel model =(DefaultTableModel) createbill.getModel();
    
                 String s2= qntity.getText();//quantity
                 Connection con2=myConnection();
   PreparedStatement p;
   String result = null;
   try{
                PreparedStatement prs;
                 String pr="SELECT `price` from `booktbl` where `title`='"+pronme.getText()+"'";
                 //mrp
                 prs=con.prepareStatement(pr);
                 ResultSet f=prs.executeQuery(pr);
                 String pid;
                  
                 while(f.next())
                 {
                
           pid = f.getString("price");
                 
                 //String s3=jTextField6.getText();
                 //int d=Integer.parseInt(s3);
                 int a=Integer.parseInt(pid);
                 System.out.println(pid);
                 int b;
                  b = Integer.parseInt(s2); 
                 int c = a * b;
                 //int e = c -((d/100)*c);
                 result=String.valueOf(c);
                 
                 //getsum();
                 }
                 model.addRow(new Object[]{pronme.getText(),qntity.getText(),result});
   }    catch (SQLException ex) {
            Logger.getLogger(createbill.class.getName()).log(Level.SEVERE, null, ex);
        }
               }
            //System.out.println(bid);

           /*String sql7="UPDATE billfinal SET billid="+bl_id+"where custname='"+cusname.getText()+"' AND phno='"+ph.getText()+"'";
           prest7 = con.prepareStatement(sql7);
           prest7.executeUpdate();*/
            
            
            
           
           /*if(count>0){

               int i = okcancel("Bill has been Added?");

               System.out.println("ret:"+i);

                  //optio/nPane.setVisible(true);

                  new createbill().setVisible(true);

                  dispose();

                  con.close();

           }*/

          
          

          

       } catch (SQLException ex) {

            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

        }
       
                 // Update query;
                 //String sql1="UPDATE `stock` SET `available`=`available` - '"+qntity.getText()+"' WHERE `id`='"+String.valueOf(jComboBox2.getSelectedItem())+"'";
     //Connection con;
   //Statement st;
  // ResultSet rs1;
     try{
         //con=DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "root");
            //st=con.createStatement();  
            //st.setString(1, tmp);
            //st.executeUpdate(sql1);
            
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//address        // TODO add your handling code here:
        Connection con = myConnection();

       try{

           String sql3="INSERT INTO billmaster(`cname`,`address`,`phone`) VALUES (?,?,?)";
           String sql_3="INSERT INTO customer(`cname`,`address`,`phone`) VALUES (?,?,?)";
           //String sql="INSERT INTO bill(`productid`,`productname`,`quantity`,`price`) VALUES (?,?,?,(SELECT price from product))";

                            //name given in the table

           //String sql2="UPDATE bill SET lineprice=quantity*price";
 

           PreparedStatement prest,prest2,prest3,prest_3;

           prest3 = con.prepareStatement(sql3);
            prest_3 = con.prepareStatement(sql_3);
           //prest = con.prepareStatement(sql);
           //prest2 = con.prepareStatement(sql2);
           Date date = new Date();
            dte.setDate(date);
            
           //Date date = dte.getDate();
           String strDate = DateFormat.getDateInstance().format(date);
           
           prest3.setString(1, cusname.getText());
           
           prest3.setString(2,addrs.getText());
           prest3.setString(3, ph.getText());
           
           prest_3.setString(1, cusname.getText());
           
           prest_3.setString(2,addrs.getText());
           prest_3.setString(3, ph.getText());
           //prest3.setString(4,strDate);
           

           

            // n is the variable name for the text field. To add variable name right click the text field->change variablename.

           
           
           //prest.setString(1,proid.getText());
           
           //prest.setString(2,pronme.getText());
           
           //prest.setString(3,qntity.getText());
           
           
           
           

           

           

 

           int bm=prest3.executeUpdate();
           int cd=prest_3.executeUpdate();
           //int count = prest.executeUpdate();
           //int lp = prest2.executeUpdate();

           /*if(bm>0){

               int i = okcancel("Customer has been Added?");

               System.out.println("ret:"+i);

                  //optio/nPane.setVisible(true);

                  new createbill().setVisible(true);

                  dispose();

                  con.close();

           }*/

          

          

       } catch (SQLException ex) {

            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection();

       try{

           
           //String sql3="INSERT INTO billmaster(`custname`,`date`) VALUES (?,?)";
          
           
 

           

           //prest3 = con.prepareStatement(sql3);
           
           
           
           //Date date = dte.getDate();
           //String strDate = DateFormat.getDateInstance().format(date);
           
           //prest3.setString(1, cusname.getText());
           //prest3.setString(2,strDate);

           

            // n is the variable name for the text field. To add variable name right click the text field->change variablename.

           
           
           
           
           
           String cn=cusname.getText();
           String phn=ph.getText();
           int pho=Integer.parseInt(phn);
           
           //prest6.setString(1,cn);
       //prest6.setInt(2,pho);
           
           
       
       
       
           
         
           
           
           
           
           
           

           

           

 

           //int bm=prest3.executeUpdate();
           
            
            
            //System.out.println(bid);

           String sql7="UPDATE billfinal SET billid=? where cname='"+cusname.getText()+"' AND phone='"+ph.getText()+"'";
           String sql8="UPDATE billfinal SET lineprice=quantity*price";
           //String sql9="UPDATE billfinal SET date=(select date from billmaster where billid='"+bl_id+"') where billid='"+bl_id+"'";
           //System.out.println(bl_id);
           PreparedStatement prest7,prest8,prest9;
           
           prest7 = con.prepareStatement(sql7);
           prest8 = con.prepareStatement(sql8);
           //prest9 = con.prepareStatement(sql9);
           prest7.setInt(1, bl_id);
           
           prest7.executeUpdate();
           prest8.executeUpdate();
           //prest9.executeUpdate();
            getsum();
            
            
           
           /*if(count>0){

               int i = okcancel("Bill has been Added?");

               System.out.println("ret:"+i);

                  //optio/nPane.setVisible(true);

                  new createbill().setVisible(true);

                  dispose();

                  con.close();

           }*/

          

          

       } catch (SQLException ex) {

            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);

        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       viewcurrentbill vc;
        try {
            vc = new viewcurrentbill();
            vc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(createbill.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    public void getsum()
      {
          int sum=0;
          for(int i=0; i<createbill.getRowCount(); i++)
          {
              sum = sum + Integer.parseInt(createbill.getValueAt(i,2).toString());
          }
          total.setText(Integer.toString(sum));
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createbill().setVisible(true);
                Date date = new Date();
            dte.setDate(date);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrs;
    private javax.swing.JTable createbill;
    public static javax.swing.JTextField cusname;
    public static com.toedter.calendar.JDateChooser dte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField ph;
    private javax.swing.JTextField pronme;
    private javax.swing.JTextField qntity;
    public static javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
