/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.mysql.cj.xdevapi.Table;
import java.awt.Component;

import java.sql.Connection;
import java.sql.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

import java.sql.DriverManager;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;
import java.text.MessageFormat;

import java.util.logging.Level;

import java.util.logging.Logger;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JTable;


import javax.swing.table.DefaultTableModel;
import static project.createbill.cusname;
import static project.createbill.ph;
import static project.users.myConnection;
//import javax.swing.text.Document;
//import static stockmanagement.addcashier.myConnection;
//import static stockmanagement.createbill.cusname;
//import static stockmanagement.createbill.ph;
/**
 *
 * @author Acer
 */
public class viewcurrentbill extends javax.swing.JFrame {

    /**
     * Creates new form viewcurrentbill
     */
    public viewcurrentbill() throws SQLException {
        initComponents();
        Dimension dim = (Toolkit.getDefaultToolkit()).getScreenSize();
        setSize(dim);
        getBillid();
        setBillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stotal = new javax.swing.JLabel();
        prnt = new javax.swing.JButton();
        bid = new javax.swing.JLabel();
        datee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(billp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 192, -1, 221));

        jLabel1.setText("BILL ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 51, -1, -1));

        jLabel2.setText("DATE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 99, -1, -1));

        jLabel3.setText("SUB TOTAL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 443, -1, -1));

        stotal.setText("jLabel4");
        jPanel1.add(stotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 443, -1, -1));

        prnt.setBackground(new java.awt.Color(102, 255, 255));
        prnt.setText("PRINT");
        prnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prntActionPerformed(evt);
            }
        });
        jPanel1.add(prnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 475, -1, -1));

        bid.setText("jLabel4");
        jPanel1.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 51, -1, -1));

        datee.setText("jLabel4");
        jPanel1.add(datee, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 99, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 490, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Object GetData(JTable billp, int row_index, int col_index){
return billp.getModel().getValueAt(row_index, col_index);
}

    private void prnt() throws FileNotFoundException, DocumentException, PrinterException{
        int count=billp.getRowCount();
        Document document=new Document();
       PdfWriter.getInstance(document,new FileOutputStream("C:\\Users\\HP\\OneDrive\\Desktop\\bill"+bid.getText()+".pdf"));
       
      document.open(); 
      
      document.add(new Paragraph("                         BOOK STORE"));
      document.add(new Paragraph("  "));
      document.add(new Paragraph("  "));
      document.add(new Paragraph(jLabel1.getText()+bid.getText()));
      document.add(new Paragraph(jLabel2.getText()+datee.getText()));
      document.add(new Paragraph("Customer ID :"+cid));
      document.add(new Paragraph("  "));
      document.add(new Paragraph("  "));
      document.add(new Paragraph("  "));
      PdfPTable tab=new PdfPTable(4);
      //tab.addCell("Product ID");
      tab.addCell("Title");
      tab.addCell("Quantity");
      tab.addCell("Price");
      tab.addCell("Total");
        for(int i=0;i<count;i++){
            
            Object obj1 = GetData(billp, i, 0);
            Object obj2 = GetData(billp, i, 1);
            Object obj3 = GetData(billp, i, 2);
            Object obj4 = GetData(billp, i, 3);
            //System.out.println("working");
            //Object obj5 = GetData(billp, i, 4);
            
            String value1=obj1.toString();
            String value2=obj2.toString();
            String value3=obj3.toString();
            String value4=obj4.toString();
            //String value5=obj5.toString();

            tab.addCell(value1);
            tab.addCell(value2);
            tab.addCell(value3);
            tab.addCell(value4);
            //tab.addCell(value5);
        }
      
      document.add(tab);
      document.add(new Paragraph("  "));
      document.add(new Paragraph("  "));
      document.add(new Paragraph("  "));
      document.add(new Paragraph("                                                                                               "+jLabel3.getText()+"Rs."+stotal.getText()));
     
      document.close();
    }
    
    private void prntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prntActionPerformed
        try {
            // TODO add your handling code here:
            prnt();
            /*MessageFormat header=new MessageFormat(jLabel1.getText());
            MessageFormat footer=new MessageFormat("Page{0,number,integer}");
            
            try{
            
            billp.print(JTable.PrintMode.NORMAL, header, footer );
            }
            catch(java.awt.print.PrinterException e)
            {
            System.err.format("Cannot print %%n",e.getMessage());
            }*/
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(viewcurrentbill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PrinterException ex) {
            Logger.getLogger(viewcurrentbill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_prntActionPerformed
String bllid=null;
    /**
     * @param args the command line arguments
     */
    
    String cid;
    private void setBillTableData(){

    Connection con = myConnection();

       try{

PreparedStatement prest,prest_cid;

String sql ="select `title`,`quantity`,`price`,`lineprice` from billfinal where billid="+bllid;
String sql_cid ="select `id` from customer where cname='"+cusname.getText()+"'";
prest_cid= con.prepareStatement(sql_cid);
ResultSet rs_cid = prest_cid.executeQuery(sql_cid);
while(rs_cid.next())
{
    cid = rs_cid.getString("id");
}
prest= con.prepareStatement(sql);


ResultSet rs = prest.executeQuery(sql);


 

while(rs.next()){

   
   //String id  = String.valueOf(rs.getInt("productid"));

   String fn = rs.getString("title");

      String mn = rs.getString("quantity");

            String st = rs.getString("price");
            
            String lp = rs.getString("lineprice");

            String tbData[]={fn,mn,st,lp};

            DefaultTableModel tblModel=(DefaultTableModel)billp.getModel();

            tblModel.addRow(tbData);

 

       }

       }catch (SQLException ex) {

            Logger.getLogger(viewcurrentbill.class.getName()).log(Level.SEVERE, null, ex);

        }

    }
    
    public void getBillid() throws SQLException
    {
        Connection con = myConnection();
        var cnm=createbill.cusname.getText();
        var phn=createbill.cusname.getText();
        String sql8="SELECT billid FROM billfinal where cname='"+cusname.getText()+"' AND phone='"+ph.getText()+"'";
        PreparedStatement prest8;
        prest8 = con.prepareStatement(sql8);
        ResultSet biid=prest8.executeQuery(sql8);
                 
                 while(biid.next())
                 {
                
            bllid = biid.getString("billid");
                 }
             
        //String sql9="SELECT date FROM billmaster where billid="+bllid;
        //PreparedStatement prest9;
        //prest9 = con.prepareStatement(sql9);
        //ResultSet dte=prest9.executeQuery(sql9);
          //       String dt=null;
            //     while(dte.next())
            //     {
                
            //dt = dte.getString("date");
              //   }
              
              Date date = new Date();
              SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy");
              String dt = formatter.format(date);
                 bid.setText(bllid);
                 datee.setText(dt);
                 String st= createbill.total.getText();
                 stotal.setText(st);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewcurrentbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewcurrentbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewcurrentbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewcurrentbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewcurrentbill().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(viewcurrentbill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bid;
    private javax.swing.JTable billp;
    private javax.swing.JLabel datee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prnt;
    private javax.swing.JLabel stotal;
    // End of variables declaration//GEN-END:variables
}
